### ISSUE TITLE
Default random task colors on frontend if none were passed

### ISSUE THREAD

**Issue by irdkwmnsb** [icpc/live-v3#10]

**Comment by niemela** [comment]
@lperovskaya `null` and missing is supposed to be the same according to the CLICS Contest API spec. In your example above, no color was provided to the upstream system, and it therefore outputs `null` for color.

**Comment by lperovskaya** [comment]
Tmp solution: advanced.json with the following config

{
 "problemOverrides": {
"A":{"color":"#e6194B"},
"B":{"color":"#3cb44b"},
"C":{"color":"#ffe119"},
"D":{"color":"#4363d8"},
"E":{"color":"#f58231"},
"F":{"color":"#42d4f4"},
"G":{"color":"#f032e6"},
"H":{"color":"#fabed4"},
"I":{"color":"#469990"},
"J":{"color":"#dcbeff"},
"K":{"color":"#9A6324"},
"L":{"color":"#fffac8"},
"M":{"color":"#800000"},
"N":{"color":"#aaffc3"},
"O":{"color":"#000075"},
"P":{"color":"#a9a9a9"}
  }
}

**Comment by lperovskaya** [comment]
use advanced.json instead
https://github.com/icpc/live-v3/blob/main/advanced.json.md
