### ISSUE TITLE
Grabbing contestant screens with webrtc

### ISSUE THREAD

**Issue by irdkwmnsb** [icpc/live-v3#12]

**Comment by niemela** [comment]
This would be *very* useful for regionals.

**Comment by irdkwmnsb** [comment]
I am working on it in another repository (to be published).
Still needs support on the overlay part.
Reopening this when it's ready.

**Comment by lperovskaya** [comment]
[niemela](https://github.com/irdkwmnsb/webrtc-grabber/releases/tag/v0.0.1-alpha)

**Comment by lperovskaya** [comment]
https://github.com/irdkwmnsb/webrtc-grabber/releases/tag/v0.0.1-alpha

**Comment by irdkwmnsb** [comment]
[The repository](https://github.com/irdkwmnsb/webrtc-grabber) is now open, but it's still very early in development.
Hoping to experiment with it some more later this year.
