### ISSUE TITLE
Show backend log in separate admin page

### ISSUE THREAD

**Issue by kunyavskiy** [icpc/live-v3#24]
No api for now

**Comment by lperovskaya** [comment]
https://github.com/icpc/live-v3/commit/9215e4d05fb0a980450a6f26a11b93ffe6cb1454

**Comment by lperovskaya** [comment]
was "Drop old advanced properties from admin and maybe support new one"

**Comment by lperovskaya** [comment]
need new WS with log except the part that writes into that WS

**Comment by irdkwmnsb** [comment]
Added in 678aa8f712779a8197840cc9a5e766294891f272.
(pending release)
