### ISSUE TITLE
Think about the time when submits are in the queue

### ISSUE THREAD

**Issue by lperovskaya** [icpc/live-v3#38]
With a large number of submits, they do not fit, it does not look very good.

Perhaps it is necessary to hide them faster, since breaking news may not fit.

**Comment by irdkwmnsb** [comment]
Maybe we can squeeze them in height? Remove extra space/padding or change the font size?

**Comment by irdkwmnsb** [comment]
Some example for this is being designed for v4. Once we have all the designs and it's still going to be an issue - we will reopen/create a new issue for it.
