### ISSUE TITLE
Move ticker for TA live to main project. Multiline scoreboard, for example

### ISSUE THREAD

**Issue by lperovskaya** [icpc/live-v3#40]

**Comment by irdkwmnsb** [comment]
TA = Tinkoff Arena
see hacks/nerc-2021

**Comment by irdkwmnsb** [comment]
Not sure if it's that important. It was different there because we had more space and hence pixels. It just won't look pretty I think. But we need to discuss and maybe try it?

**Comment by niemela** [comment]
@irdkwmnsb Is there a screenshot (or similar) of what this looked like?

**Comment by lperovskaya** [comment]
on Northern Eurasia Venue we had a ribbon screen that was managed from a 1920:1080 screen split into 8 horizontal lines, each responsible for the corresponding ribbon segment.

Max based it on a custom overlayticker installation, where multiple tickers are all controlled from the same webadmin interface. Ticker supports text messages (used for "do not touch anything" announcements and award ceremony), contest clock and custom instance of ticker scoreboard that fit two lines of teams at once (default only supports one line of teams)

https://user-images.githubusercontent.com/2369861/167072100-5138e5fa-8103-40b7-b526-434edbf404c0.mp4


https://user-images.githubusercontent.com/2369861/167072106-559006d2-bb06-4ea6-b541-2900fe370753.mp4


https://user-images.githubusercontent.com/2369861/167072115-206d70d7-6b27-41c7-92a8-a5f03fdd8f06.mp4

![image](https://user-images.githubusercontent.com/2369861/167072371-7d1d8096-81bd-46f3-9e2f-c758f854b771.png)
![OujzAfJN1UExE414d0HZL2TtxMens83HXm4SXM_7UfZlT0hDFP_jHxrgNSsauT3Wm_aleV78V6eCCeNRRwYh_QkX](https://user-images.githubusercontent.com/2369861/167072680-ed61c18d-5f5c-4282-8464-94c5c18c3529.jpg)
![apieQxCPaCxydLc1n2ZuqzogCzze2Uj6hOkj9aBR7fbAszM3sp2gZNxAtgO3GHZQzcohijtZrlaG0Hi64970Rpdy](https://user-images.githubusercontent.com/2369861/167072685-7e1cab58-32bf-4990-b978-042974e8775c.jpg)
