### ISSUE TITLE
feat: Support updated event feed format

### ISSUE THREAD

**Issue by niemela** [icpc/live-v3#59]
Support the updated event feed format, as defined here:
https://ccs-specs.icpc.io/master/contest_api#notification-format

**Comment by kunyavskiy** [comment]
Do you think we need to support both new and old format? Is there any diff between specs, we can check?

**Comment by niemela** [comment]
I don't think we need to support the old as well.

You can see the old specs here https://ccs-specs.icpc.io/2021-11/contest_api#event-feed .

**Comment by niemela** [comment]
Updated links:

Old specs: https://ccs-specs.icpc.io/2021-11/
New specs: https://ccs-specs.icpc.io/2022-07/

There is a changelog between them at the latter link.

**Comment by lperovskaya** [comment]
Supported, old version temporarily supported via 
`feed_version=2020_03`
