### ISSUE TITLE
bug: Scoreboard scrolling works strange, when teams appearing while scoreboard is shown

### ISSUE THREAD

**Issue by kunyavskiy** [icpc/live-v3#63]
You can check it by enabling 
```
{
  "scoreboardOverrides": {
    "showTeamsWithoutSubmissions": false
  }
}
```
in advanced settings.

**Comment by irdkwmnsb** [comment]
should be fixed by #32

**Comment by lperovskaya** [comment]
Scaling breaks in case of new appearing teams. Refresh, obviously, fixes it
![image](https://user-images.githubusercontent.com/2369861/187191492-0d214100-b93a-49a8-ae14-42e2fdcc5ba7.png)

**Comment by irdkwmnsb** [comment]
Fixed in Dhaka sprint/hackathon
