### ISSUE TITLE
feat: allow usage of locally hosted of images from Titles view 

### ISSUE THREAD

**Issue by xiaowuc1** [icpc/live-v3#76]
## Feature description
Right now, images are required to be hosted via some external URL. Make it possible to use self-hosted images.
## Motivation and possible use case
Two scenarios - one is that you are running a contest locally and cannot connect externally for some reason. Another is that you don't want assets to be publicly accessible at all.

**Comment by lperovskaya** [comment]
works now, use "media" tab of admin
